apiVersion: v2
name: cert-manager-wrapper
version: 1.16.1
appVersion: v1.16.1

description: A Helm chart for cert-manager wrapper
type: application

dependencies:
  - name: cert-manager
    version: 1.16.1
    repository: https://charts.jetstack.io